// Code generated by redwood. DO NOT EDIT.
package main

// Request-body assembly from flattened inputs.
//
// A body-taking command layers three input sources, deepest wins:
//
//	-f/--file <doc>          the whole body (YAML or JSON)
//	--<node> <doc>           a document for one subtree
//	--<leaf> <value>         one typed value
//
// Discriminated unions are stamped from the arm whose inputs were used (or
// an explicit tag), documents are checked against the request schema
// (unknown fields dropped with a warning, enum short forms expanded,
// required paths reported by flag name), and partial updates derive their
// field mask from the paths that were set.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"sigs.k8s.io/yaml"
)

// ---- document and value parsing ---------------------------------------------

// parseDocument decodes a YAML or JSON document (JSON is YAML). Numbers stay
// json.Number so large integers round-trip untouched; null is rejected — a
// structured input holds a value, never the absence of one.
func parseDocument(flag, text string) (any, error) {
	if strings.TrimSpace(text) == "" {
		return nil, fmt.Errorf("--%s: empty document", flag)
	}
	jsonBytes, err := yaml.YAMLToJSON([]byte(text))
	if err != nil {
		return nil, fmt.Errorf("--%s: invalid YAML/JSON: %w", flag, err)
	}
	dec := json.NewDecoder(bytes.NewReader(jsonBytes))
	dec.UseNumber()
	var v any
	if err := dec.Decode(&v); err != nil {
		return nil, fmt.Errorf("--%s: invalid document: %w", flag, err)
	}
	if v == nil {
		return nil, fmt.Errorf("--%s: null is not a valid value; omit the flag instead", flag)
	}
	return v, nil
}

// docArg parses a document input: a literal, @path, or - (stdin).
func docArg(flag, raw string) (any, error) {
	resolved, err := resolveInput(raw)
	if err != nil {
		return nil, fmt.Errorf("--%s: %w", flag, err)
	}
	return parseDocument(flag, resolved)
}

// objectArg parses a document input that must be an object.
func objectArg(flag, raw string) (map[string]any, error) {
	v, err := docArg(flag, raw)
	if err != nil {
		return nil, err
	}
	obj, ok := v.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("--%s: expected an object (YAML mapping or JSON object)", flag)
	}
	return obj, nil
}

// stringArg expands @path and - (stdin) for a plain string input; "@@"
// escapes a literal leading "@".
func stringArg(flag, raw string) (string, error) {
	if strings.HasPrefix(raw, "@@") {
		return raw[1:], nil
	}
	if raw == "-" || strings.HasPrefix(raw, "@") {
		v, err := resolveInput(raw)
		if err != nil {
			return "", fmt.Errorf("--%s: %w", flag, err)
		}
		return v, nil
	}
	return raw, nil
}

// looksLikeDocument reports whether a repeatable input's value is a
// document (file, stdin, JSON/YAML collection) rather than an entry or
// shorthand item.
func looksLikeDocument(raw string) bool {
	t := strings.TrimSpace(raw)
	return raw == "-" || strings.HasPrefix(raw, "@") || strings.HasPrefix(t, "{") ||
		strings.HasPrefix(t, "[") || strings.Contains(t, "\n")
}

// enumSpec is an enum's accepted wire values and their short forms
// (parallel slices; Short is empty when no short forms exist).
type enumSpec struct {
	Values []string
	Short  []string
}

func (e enumSpec) choices() string {
	if len(e.Short) == len(e.Values) && len(e.Short) > 0 {
		return strings.Join(e.Short, ", ")
	}
	return strings.Join(e.Values, ", ")
}

// parse maps a wire value, a short form, or a case-insensitive spelling of
// either to the wire value.
func (e enumSpec) parse(flag, raw string) (string, error) {
	for i, v := range e.Values {
		if v == raw {
			return v, nil
		}
		if i < len(e.Short) && strings.EqualFold(e.Short[i], raw) {
			return v, nil
		}
	}
	for _, v := range e.Values {
		if strings.EqualFold(v, raw) {
			return v, nil
		}
	}
	return "", fmt.Errorf("--%s: invalid value %q (valid: %s)", flag, raw, e.choices())
}

// scalarKind selects how one text value becomes a JSON value.
type scalarKind int

const (
	scalarString scalarKind = iota
	scalarBool
	scalarInt
	scalarFloat
)

// scalarValue converts one text value; enum (when non-nil) applies first.
func scalarValue(flag, raw string, kind scalarKind, enum *enumSpec) (any, error) {
	if enum != nil {
		return enum.parse(flag, raw)
	}
	switch kind {
	case scalarBool:
		v, err := strconv.ParseBool(raw)
		if err != nil {
			return nil, fmt.Errorf("--%s: invalid boolean %q", flag, raw)
		}
		return v, nil
	case scalarInt:
		if !isInteger(raw) {
			return nil, fmt.Errorf("--%s: invalid integer %q", flag, raw)
		}
		return json.Number(raw), nil
	case scalarFloat:
		if _, err := strconv.ParseFloat(raw, 64); err != nil {
			return nil, fmt.Errorf("--%s: invalid number %q", flag, raw)
		}
		return json.Number(raw), nil
	default:
		return raw, nil
	}
}

// isInteger accepts an optionally signed digit string of any length (the
// value travels as a JSON number, so int64 is not the limit).
func isInteger(raw string) bool {
	digits := strings.TrimPrefix(strings.TrimPrefix(raw, "-"), "+")
	if digits == "" {
		return false
	}
	for _, r := range digits {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

// parseKV splits KEY=VALUE on the first '='; the value may be empty.
func parseKV(flag, raw string) (string, string, error) {
	i := strings.Index(raw, "=")
	if i <= 0 {
		return "", "", fmt.Errorf("--%s: expected KEY=VALUE, got %q", flag, raw)
	}
	return raw[:i], raw[i+1:], nil
}

// looksLikeEntry reports whether a value is a KEY=VALUE / KEY:=DOC entry.
func looksLikeEntry(raw string) bool {
	if looksLikeDocument(raw) {
		return false
	}
	i := strings.Index(raw, "=")
	if i <= 0 {
		return false
	}
	key := strings.TrimSuffix(raw[:i], ":")
	if key == "" {
		return false
	}
	for _, r := range key {
		if !(r == '_' || r == '-' || r == '.' || r == '/' || (r >= '0' && r <= '9') ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')) {
			return false
		}
	}
	return true
}

// parseEntry reads KEY=VALUE (a string) or KEY:=DOC (a typed YAML/JSON
// value, @path or - allowed) for untyped maps.
func parseEntry(flag, raw string) (string, any, error) {
	i := strings.Index(raw, "=")
	if i <= 0 {
		return "", nil, fmt.Errorf("--%s: expected KEY=VALUE, KEY:=JSON, or a document, got %q", flag, raw)
	}
	key, value := raw[:i], raw[i+1:]
	if !strings.HasSuffix(key, ":") {
		return key, value, nil
	}
	key = strings.TrimSuffix(key, ":")
	doc, err := docArg(flag, value)
	if err != nil {
		return "", nil, err
	}
	return key, doc, nil
}

// shorthandField describes one key of a `k=v,k=v` list item.
type shorthandField struct {
	Wire     string
	Key      string
	Kind     scalarKind
	Enum     *enumSpec
	Required bool
}

// shorthandSpec describes a flat list item: its fields, and (when the item
// is `{name|key, value}`) the two wire names of the NAME=VALUE pair form.
type shorthandSpec struct {
	Fields    []shorthandField
	PairKey   string
	PairValue string
}

func (s shorthandSpec) field(key string) *shorthandField {
	for i := range s.Fields {
		if s.Fields[i].Key == key || s.Fields[i].Wire == key {
			return &s.Fields[i]
		}
	}
	return nil
}

func (s shorthandSpec) keys() string {
	keys := make([]string, len(s.Fields))
	for i, f := range s.Fields {
		keys[i] = f.Key
	}
	return strings.Join(keys, ", ")
}

// splitShorthand splits `k=v,k=v` on commas outside double quotes and
// strips the quotes (`k="a,b"`).
func splitShorthand(raw string) []string {
	var parts []string
	var current strings.Builder
	quoted := false
	for _, r := range raw {
		switch {
		case r == '"':
			quoted = !quoted
		case r == ',' && !quoted:
			parts = append(parts, current.String())
			current.Reset()
		default:
			current.WriteRune(r)
		}
	}
	parts = append(parts, current.String())
	return parts
}

// parseShorthand reads one list item: `k=v,k=v` over the item's fields, or
// `NAME=VALUE` when the item has a pair form and NAME is not a field.
func parseShorthand(flag, raw string, spec shorthandSpec) (map[string]any, error) {
	item := map[string]any{}
	if spec.PairKey != "" {
		if i := strings.Index(raw, "="); i > 0 && spec.field(raw[:i]) == nil {
			item[spec.PairKey] = raw[:i]
			item[spec.PairValue] = raw[i+1:]
			return item, nil
		}
	}
	for _, part := range splitShorthand(raw) {
		if strings.TrimSpace(part) == "" {
			continue
		}
		k, v, err := parseKV(flag, part)
		if err != nil {
			return nil, fmt.Errorf("--%s: expected %s as key=value pairs, got %q", flag, spec.keys(), raw)
		}
		f := spec.field(k)
		if f == nil {
			return nil, fmt.Errorf("--%s: unknown key %q (valid: %s)", flag, k, spec.keys())
		}
		value, err := scalarValue(flag, v, f.Kind, f.Enum)
		if err != nil {
			return nil, err
		}
		item[f.Wire] = value
	}
	for _, f := range spec.Fields {
		if _, ok := item[f.Wire]; f.Required && !ok {
			return nil, fmt.Errorf("--%s: %s is required in %q", flag, f.Key, raw)
		}
	}
	return item, nil
}

// ---- body builder -----------------------------------------------------------

// bodyBuilder accumulates the request body and remembers which inputs set
// which paths (for union conflicts and the update mask).
type bodyBuilder struct {
	body     map[string]any
	paths    map[string]bool
	flags    map[string][]string
	explicit map[string]string
}

func newBodyBuilder() *bodyBuilder {
	return &bodyBuilder{
		body:     map[string]any{},
		paths:    map[string]bool{},
		flags:    map[string][]string{},
		explicit: map[string]string{},
	}
}

func dottedPath(path []string) string {
	return strings.Join(path, ".")
}

func (b *bodyBuilder) record(path []string, flag string) {
	key := dottedPath(path)
	b.paths[key] = true
	b.flags[key] = append(b.flags[key], "--"+flag)
}

// container returns the object at path, creating objects along the way.
func (b *bodyBuilder) container(flag string, path []string) (map[string]any, error) {
	current := b.body
	for i, seg := range path {
		next, present := current[seg]
		if !present {
			created := map[string]any{}
			current[seg] = created
			current = created
			continue
		}
		obj, ok := next.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("--%s: %s is not an object", flag, dottedPath(path[:i+1]))
		}
		current = obj
	}
	return current, nil
}

// set stores one value at path (overwriting).
func (b *bodyBuilder) set(flag string, path []string, v any) error {
	parent, err := b.container(flag, path[:len(path)-1])
	if err != nil {
		return err
	}
	parent[path[len(path)-1]] = v
	b.record(path, flag)
	return nil
}

// merge deep-merges an object document at path (the document wins on
// conflicts; lists replace).
func (b *bodyBuilder) merge(flag string, path []string, doc map[string]any) error {
	target, err := b.container(flag, path)
	if err != nil {
		return err
	}
	mergeInto(target, doc)
	if len(path) == 0 {
		for key := range doc {
			b.record([]string{key}, flag)
		}
		return nil
	}
	for key := range doc {
		b.record(append(append([]string{}, path...), key), flag)
	}
	return nil
}

func mergeInto(dst, src map[string]any) {
	for k, v := range src {
		if sv, ok := v.(map[string]any); ok {
			if dv, ok := dst[k].(map[string]any); ok {
				mergeInto(dv, sv)
				continue
			}
		}
		dst[k] = v
	}
}

// appendItem adds one element to the list at path.
func (b *bodyBuilder) appendItem(flag string, path []string, v any) error {
	parent, err := b.container(flag, path[:len(path)-1])
	if err != nil {
		return err
	}
	key := path[len(path)-1]
	existing, present := parent[key]
	if !present {
		parent[key] = []any{v}
	} else {
		list, ok := existing.([]any)
		if !ok {
			return fmt.Errorf("--%s: %s is not a list", flag, dottedPath(path))
		}
		parent[key] = append(list, v)
	}
	b.record(path, flag)
	return nil
}

// putEntry sets one key of the map at path.
func (b *bodyBuilder) putEntry(flag string, path []string, key string, v any) error {
	target, err := b.container(flag, path)
	if err != nil {
		return err
	}
	target[key] = v
	b.record(path, flag)
	return nil
}

// lookup returns the value at path, ok=false when any step is missing.
func (b *bodyBuilder) lookup(path []string) (any, bool) {
	return lookupPath(b.body, path)
}

// applyFile merges the whole-body document read from a file path (or
// stdin for "-"), dropping fields the request schema does not accept (a
// warning; an error under strict).
func (b *bodyBuilder) applyFile(flag, raw string, schema *schemaNode, strict bool) error {
	if raw != "-" {
		raw = "@" + strings.TrimPrefix(raw, "@")
	}
	doc, err := objectArg(flag, raw)
	if err != nil {
		return err
	}
	if err := b.checkUnknown(flag, nil, doc, schema, strict); err != nil {
		return err
	}
	return b.merge(flag, nil, doc)
}

// applyDoc merges a subtree document at path.
func (b *bodyBuilder) applyDoc(flag string, path []string, raw string, schema *schemaNode, strict bool) error {
	doc, err := objectArg(flag, raw)
	if err != nil {
		return err
	}
	if err := b.checkUnknown(flag, path, doc, schema, strict); err != nil {
		return err
	}
	return b.merge(flag, path, doc)
}

func (b *bodyBuilder) checkUnknown(flag string, path []string, doc map[string]any, schema *schemaNode, strict bool) error {
	if schema == nil {
		return nil
	}
	node := schema.at(path)
	if node == nil {
		return nil
	}
	dropped := stripUnknown(schema, node, doc, path)
	if len(dropped) == 0 {
		return nil
	}
	if strict {
		return fmt.Errorf("--%s: unknown field(s): %s", flag, strings.Join(dropped, ", "))
	}
	fmt.Fprintf(os.Stderr, "warning: --%s: ignoring unknown field(s): %s\n", flag, strings.Join(dropped, ", "))
	return nil
}

// applyEntries reads repeatable KEY=VALUE (typed by kind/enum) or a
// document for a scalar map.
func (b *bodyBuilder) applyEntries(flag string, path []string, raws []string, kind scalarKind, enum *enumSpec) error {
	for _, raw := range raws {
		if looksLikeDocument(raw) {
			doc, err := objectArg(flag, raw)
			if err != nil {
				return err
			}
			for k, v := range doc {
				if err := b.putEntry(flag, path, k, v); err != nil {
					return err
				}
			}
			continue
		}
		k, v, err := parseKV(flag, raw)
		if err != nil {
			return err
		}
		value, err := scalarValue(flag, v, kind, enum)
		if err != nil {
			return err
		}
		if err := b.putEntry(flag, path, k, value); err != nil {
			return err
		}
	}
	return nil
}

// applyEntryDocs reads repeatable entries (KEY=VALUE, KEY:=DOC) or whole
// documents for an untyped value.
func (b *bodyBuilder) applyEntryDocs(flag string, path []string, raws []string) error {
	for _, raw := range raws {
		if looksLikeEntry(raw) {
			k, v, err := parseEntry(flag, raw)
			if err != nil {
				return err
			}
			if err := b.putEntry(flag, path, k, v); err != nil {
				return err
			}
			continue
		}
		doc, err := docArg(flag, raw)
		if err != nil {
			return err
		}
		if obj, ok := doc.(map[string]any); ok {
			if err := b.merge(flag, path, obj); err != nil {
				return err
			}
			continue
		}
		if len(path) == 0 {
			return fmt.Errorf("--%s: expected an object", flag)
		}
		if err := b.set(flag, path, doc); err != nil {
			return err
		}
	}
	return nil
}

// applyScalarItems appends repeatable typed values to a list.
func (b *bodyBuilder) applyScalarItems(flag string, path []string, raws []string, kind scalarKind, enum *enumSpec) error {
	for _, raw := range raws {
		value, err := scalarValue(flag, raw, kind, enum)
		if err != nil {
			return err
		}
		if err := b.appendItem(flag, path, value); err != nil {
			return err
		}
	}
	return nil
}

// applyDocItems appends repeatable object documents to a list.
func (b *bodyBuilder) applyDocItems(flag string, path []string, raws []string) error {
	for _, raw := range raws {
		doc, err := docArg(flag, raw)
		if err != nil {
			return err
		}
		if err := b.appendItem(flag, path, doc); err != nil {
			return err
		}
	}
	return nil
}

// applyShorthandItems appends repeatable `k=v,k=v` items (or documents).
func (b *bodyBuilder) applyShorthandItems(flag string, path []string, raws []string, spec shorthandSpec) error {
	for _, raw := range raws {
		if looksLikeDocument(raw) {
			doc, err := objectArg(flag, raw)
			if err != nil {
				return err
			}
			if err := b.appendItem(flag, path, doc); err != nil {
				return err
			}
			continue
		}
		item, err := parseShorthand(flag, raw, spec)
		if err != nil {
			return err
		}
		if err := b.appendItem(flag, path, item); err != nil {
			return err
		}
	}
	return nil
}

// ---- unions -------------------------------------------------------------------

type unionArm struct {
	Tag  string
	Keys []string
	Init []string
}

// unionParent locates the arm a nested union lives in: the union is only
// evaluated when that arm is selected.
type unionParent struct {
	Path          []string
	Discriminator string
	Tag           string
}

type unionSpec struct {
	Flag          string
	Path          []string
	Discriminator string
	Arms          []unionArm
	Required      bool
	Inferable     bool
	Parent        *unionParent
}

func (u unionSpec) tags() string {
	tags := make([]string, len(u.Arms))
	for i, a := range u.Arms {
		tags[i] = a.Tag
	}
	return strings.Join(tags, ", ")
}

// matchTag maps a spelling (wire tag, kebab/lowercase) to the wire tag.
func (u unionSpec) matchTag(raw string) string {
	norm := func(s string) string {
		return strings.ToLower(strings.NewReplacer("-", "", "_", "").Replace(s))
	}
	for _, a := range u.Arms {
		if a.Tag == raw || norm(a.Tag) == norm(raw) {
			return a.Tag
		}
	}
	return ""
}

// applyUnionFlag reads the tag input: an arm name, or a document for the
// whole union value.
func (b *bodyBuilder) applyUnionFlag(u unionSpec, raw string, schema *schemaNode, strict bool) error {
	if tag := u.matchTag(raw); tag != "" {
		b.explicit[dottedPath(u.Path)] = tag
		return nil
	}
	if !looksLikeDocument(raw) {
		return fmt.Errorf("--%s: invalid value %q (valid: %s, or a document)", u.Flag, raw, u.tags())
	}
	return b.applyDoc(u.Flag, u.Path, raw, schema, strict)
}

// resolveUnion stamps the discriminator: an explicit tag, the tag already
// in the value, or the single arm whose inputs were used. Inputs from two
// arms, or an explicit tag contradicting them, are usage errors.
func (b *bodyBuilder) resolveUnion(u unionSpec) error {
	key := dottedPath(u.Path)
	explicit := b.explicit[key]
	if u.Parent != nil {
		parent, _ := b.lookup(u.Parent.Path)
		obj, _ := parent.(map[string]any)
		if tag, _ := obj[u.Parent.Discriminator].(string); tag != u.Parent.Tag {
			if explicit != "" {
				return fmt.Errorf("--%s applies to the %s arm of --%s, which is not selected", u.Flag, u.Parent.Tag, dottedPath(u.Parent.Path))
			}
			return nil
		}
	}
	var obj map[string]any
	if v, ok := b.lookup(u.Path); ok {
		var isObj bool
		obj, isObj = v.(map[string]any)
		if !isObj {
			return fmt.Errorf("--%s: %s is not an object", u.Flag, key)
		}
	}
	existing := ""
	if obj != nil {
		if s, ok := obj[u.Discriminator].(string); ok {
			existing = u.matchTag(s)
			if existing == "" {
				return fmt.Errorf("--%s: unknown %s %q (valid: %s)", u.Flag, u.Discriminator, s, u.tags())
			}
		}
	}
	var present []unionArm
	for _, arm := range u.Arms {
		for _, k := range arm.Keys {
			if obj != nil {
				if _, ok := obj[k]; ok {
					present = append(present, arm)
					break
				}
			}
		}
	}
	describe := func(arm unionArm) string {
		var flags []string
		for _, k := range arm.Keys {
			prefix := key
			if prefix != "" {
				prefix += "."
			}
			flags = append(flags, b.flagsUnder(prefix+k)...)
		}
		if len(flags) == 0 {
			return fmt.Sprintf("%s inputs", arm.Tag)
		}
		return strings.Join(unique(flags), ", ")
	}
	if len(present) > 1 && u.Inferable {
		return fmt.Errorf("%s and %s are mutually exclusive (--%s arms %s and %s)",
			describe(present[0]), describe(present[1]), u.Flag, present[0].Tag, present[1].Tag)
	}
	chosen := explicit
	if chosen == "" {
		chosen = existing
	} else if existing != "" && existing != chosen {
		return fmt.Errorf("--%s %s contradicts %s: %s already in the document", u.Flag, chosen, u.Discriminator, existing)
	}
	if chosen == "" && u.Inferable && len(present) == 1 {
		chosen = present[0].Tag
	}
	if chosen == "" {
		if obj == nil && !u.Required {
			return nil
		}
		if len(present) > 0 {
			return fmt.Errorf("--%s is required: %s could belong to several arms (one of: %s)", u.Flag, describe(present[0]), u.tags())
		}
		return fmt.Errorf("--%s is required (one of: %s)", u.Flag, u.tags())
	}
	if u.Inferable {
		for _, arm := range present {
			if arm.Tag != chosen {
				return fmt.Errorf("--%s %s contradicts %s (arm %s)", u.Flag, chosen, describe(arm), arm.Tag)
			}
		}
	}
	if obj == nil {
		created, err := b.container(u.Flag, u.Path)
		if err != nil {
			return err
		}
		obj = created
	}
	obj[u.Discriminator] = chosen
	for _, arm := range u.Arms {
		if arm.Tag != chosen {
			continue
		}
		for _, k := range arm.Init {
			if _, ok := obj[k]; !ok {
				obj[k] = map[string]any{}
			}
		}
	}
	return nil
}

// flagsUnder lists the flags that set a path or anything beneath it.
func (b *bodyBuilder) flagsUnder(prefix string) []string {
	var out []string
	for path, flags := range b.flags {
		if path == prefix || strings.HasPrefix(path, prefix+".") {
			out = append(out, flags...)
		}
	}
	sort.Strings(out)
	return out
}

func unique(items []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range items {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// updateMask lists every set path (except the mask field itself) in the
// comma-separated field-mask form.
func (b *bodyBuilder) updateMask(maskField string) string {
	var paths []string
	for p := range b.paths {
		if p != maskField {
			paths = append(paths, p)
		}
	}
	sort.Strings(paths)
	return strings.Join(paths, ",")
}

// finish validates the assembled body against the request schema: enum
// short forms inside documents become wire values, and missing required
// paths are reported by flag name (flagFor maps dotted paths to flags).
func (b *bodyBuilder) finish(schema *schemaNode, flagFor map[string]string) error {
	if schema == nil {
		return nil
	}
	if err := normalizeEnums(schema, schema, b.body, nil); err != nil {
		return err
	}
	var missing []string
	checkRequired(schema, schema, b.body, nil, &missing)
	if len(missing) == 0 {
		return nil
	}
	names := make([]string, 0, len(missing))
	for _, path := range missing {
		if flag, ok := flagFor[path]; ok {
			names = append(names, flag)
		} else {
			names = append(names, path)
		}
	}
	return fmt.Errorf("required flag(s) not set: %s", strings.Join(unique(names), ", "))
}

// ---- request schema ---------------------------------------------------------

// schemaNode is the request-direction JSON Schema the generator embeds per
// command ($refs are bare names into $defs).
type schemaNode struct {
	Type                 string                 `json:"type"`
	Properties           map[string]*schemaNode `json:"properties"`
	Required             []string               `json:"required"`
	Items                *schemaNode            `json:"items"`
	AdditionalProperties *schemaNode            `json:"additionalProperties"`
	OneOf                []*schemaNode          `json:"oneOf"`
	Discriminator        *struct {
		PropertyName string `json:"propertyName"`
	} `json:"discriminator"`
	Enum      []string          `json:"enum"`
	EnumShort map[string]string `json:"enumShort"`
	Const     *string           `json:"const"`
	Ref       string            `json:"$ref"`
	Defs      map[string]*schemaNode `json:"$defs"`
}

// parseBodySchema decodes an embedded schema; the text is generator-owned,
// so a failure is a build defect, not a user error.
func parseBodySchema(text string) *schemaNode {
	var node schemaNode
	if err := json.Unmarshal([]byte(text), &node); err != nil {
		panic("invalid embedded request schema: " + err.Error())
	}
	return &node
}

// deref follows $ref chains.
func (root *schemaNode) deref(n *schemaNode) *schemaNode {
	for i := 0; n != nil && n.Ref != "" && i < 8; i++ {
		n = root.Defs[n.Ref]
	}
	return n
}

// arm picks the oneOf variant a value's discriminator selects.
func (root *schemaNode) arm(n *schemaNode, value map[string]any) *schemaNode {
	if n == nil || n.Discriminator == nil {
		return nil
	}
	tag, _ := value[n.Discriminator.PropertyName].(string)
	if tag == "" {
		return nil
	}
	for _, v := range n.OneOf {
		arm := root.deref(v)
		if arm == nil {
			continue
		}
		prop := root.deref(arm.Properties[n.Discriminator.PropertyName])
		if prop == nil {
			continue
		}
		if (prop.Const != nil && *prop.Const == tag) || (len(prop.Enum) == 1 && prop.Enum[0] == tag) {
			return arm
		}
	}
	return nil
}

// at walks properties to the schema for a path (nil through a union, which
// needs a value to pick the arm).
func (root *schemaNode) at(path []string) *schemaNode {
	n := root.deref(root)
	for _, seg := range path {
		if n == nil || n.Properties == nil {
			return nil
		}
		n = root.deref(n.Properties[seg])
	}
	return n
}

// stripUnknown removes fields no schema property accepts, returning their
// dotted paths.
func stripUnknown(root, n *schemaNode, value any, path []string) []string {
	n = root.deref(n)
	if n == nil {
		return nil
	}
	var dropped []string
	switch v := value.(type) {
	case map[string]any:
		if len(n.OneOf) > 0 {
			if arm := root.arm(n, v); arm != nil {
				return stripUnknown(root, arm, v, path)
			}
			return nil
		}
		if n.Properties == nil {
			if n.AdditionalProperties != nil {
				for k, item := range v {
					dropped = append(dropped, stripUnknown(root, n.AdditionalProperties, item, append(append([]string{}, path...), k))...)
				}
			}
			return dropped
		}
		for k, item := range v {
			prop, ok := n.Properties[k]
			if !ok {
				if n.AdditionalProperties != nil {
					continue
				}
				delete(v, k)
				dropped = append(dropped, dottedPath(append(append([]string{}, path...), k)))
				continue
			}
			dropped = append(dropped, stripUnknown(root, prop, item, append(append([]string{}, path...), k))...)
		}
	case []any:
		for i, item := range v {
			dropped = append(dropped, stripUnknown(root, n.Items, item, append(append([]string{}, path...), strconv.Itoa(i)))...)
		}
	}
	sort.Strings(dropped)
	return dropped
}

// normalizeEnums replaces enum short forms (and case variants) inside
// documents with wire values; an unknown value is a usage error.
func normalizeEnums(root, n *schemaNode, value any, path []string) error {
	n = root.deref(n)
	if n == nil {
		return nil
	}
	switch v := value.(type) {
	case map[string]any:
		if len(n.OneOf) > 0 {
			if arm := root.arm(n, v); arm != nil {
				return normalizeEnums(root, arm, v, path)
			}
			return nil
		}
		for k, item := range v {
			prop := n.Properties[k]
			if prop == nil {
				prop = n.AdditionalProperties
			}
			child := root.deref(prop)
			if child == nil {
				continue
			}
			childPath := append(append([]string{}, path...), k)
			if s, ok := item.(string); ok && len(child.Enum) > 0 {
				wire, err := enumWire(child, s, dottedPath(childPath))
				if err != nil {
					return err
				}
				v[k] = wire
				continue
			}
			if err := normalizeEnums(root, child, item, childPath); err != nil {
				return err
			}
		}
	case []any:
		child := root.deref(n.Items)
		if child == nil {
			return nil
		}
		for i, item := range v {
			childPath := append(append([]string{}, path...), strconv.Itoa(i))
			if s, ok := item.(string); ok && len(child.Enum) > 0 {
				wire, err := enumWire(child, s, dottedPath(childPath))
				if err != nil {
					return err
				}
				v[i] = wire
				continue
			}
			if err := normalizeEnums(root, child, item, childPath); err != nil {
				return err
			}
		}
	}
	return nil
}

func enumWire(n *schemaNode, raw, path string) (string, error) {
	for _, e := range n.Enum {
		if e == raw {
			return e, nil
		}
	}
	if wire, ok := n.EnumShort[strings.ToLower(raw)]; ok {
		return wire, nil
	}
	for _, e := range n.Enum {
		if strings.EqualFold(e, raw) {
			return e, nil
		}
	}
	choices := n.Enum
	if len(n.EnumShort) > 0 {
		choices = make([]string, 0, len(n.EnumShort))
		for s := range n.EnumShort {
			choices = append(choices, s)
		}
		sort.Strings(choices)
	}
	return "", fmt.Errorf("%s: invalid value %q (valid: %s)", path, raw, strings.Join(choices, ", "))
}

// checkRequired reports the deepest missing required paths. A missing
// required object is created empty and descended, so its own required
// leaves are what get named (and an object with none is simply sent as
// `{}`); a missing union reports the union itself (its tag input).
func checkRequired(root, n *schemaNode, value any, path []string, missing *[]string) {
	n = root.deref(n)
	if n == nil {
		return
	}
	obj, _ := value.(map[string]any)
	if len(n.OneOf) > 0 {
		if obj == nil {
			*missing = append(*missing, dottedPath(path))
			return
		}
		if arm := root.arm(n, obj); arm != nil {
			checkRequired(root, arm, obj, path, missing)
		} else {
			*missing = append(*missing, dottedPath(path))
		}
		return
	}
	if list, ok := value.([]any); ok {
		for i, item := range list {
			checkRequired(root, n.Items, item, append(append([]string{}, path...), strconv.Itoa(i)), missing)
		}
		return
	}
	if n.Properties == nil || obj == nil {
		return
	}
	for _, req := range n.Required {
		if obj[req] != nil {
			continue
		}
		childPath := append(append([]string{}, path...), req)
		prop := root.deref(n.Properties[req])
		switch {
		case prop == nil || prop.Const != nil:
			// A discriminator literal is stamped by union resolution.
			if prop == nil {
				*missing = append(*missing, dottedPath(childPath))
			}
		case len(prop.OneOf) > 0:
			*missing = append(*missing, dottedPath(childPath))
		case prop.Properties != nil:
			created := map[string]any{}
			obj[req] = created
			checkRequired(root, prop, created, childPath, missing)
		default:
			*missing = append(*missing, dottedPath(childPath))
		}
	}
	for k, item := range obj {
		if prop, ok := n.Properties[k]; ok {
			checkRequired(root, prop, item, append(append([]string{}, path...), k), missing)
		}
	}
}

// ---- output -------------------------------------------------------------------

// printYAML writes v as a YAML document.
func printYAML(v any) error {
	raw, err := json.Marshal(v)
	if err != nil {
		return err
	}
	out, err := yaml.JSONToYAML(raw)
	if err != nil {
		return err
	}
	_, err = os.Stdout.Write(out)
	return err
}

// printDocument renders a --dry-run body: YAML unless json was asked for.
func printDocument(mode string, v any) error {
	if mode == "json" {
		return printJSON(v)
	}
	return printYAML(v)
}
