// Code generated by redwood. DO NOT EDIT.
package commands

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
)

// tempDoc writes a document to a temp file for --file inputs.
func tempDoc(t *testing.T, content string) string {
	t.Helper()
	path := t.TempDir() + "/body.yml"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func mustJSON(t *testing.T, v any) string {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}

func TestParseDocumentAcceptsYAMLAndJSON(t *testing.T) {
	yamlDoc, err := parseDocument("spec", "name: x\ncount: 12345678901234567890\n")
	if err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, yamlDoc); got != `{"count":12345678901234567890,"name":"x"}` {
		t.Fatalf("yaml: %s", got)
	}
	jsonDoc, err := parseDocument("spec", `{"a": [1, 2]}`)
	if err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, jsonDoc); got != `{"a":[1,2]}` {
		t.Fatalf("json: %s", got)
	}
	for _, bad := range []string{"", "null", "~"} {
		if _, err := parseDocument("spec", bad); err == nil {
			t.Fatalf("%q must be rejected", bad)
		}
	}
	if _, err := objectArg("spec", "just a string"); err == nil || !strings.Contains(err.Error(), "expected an object") {
		t.Fatalf("scalar for an object input: %v", err)
	}
}

func TestStringArgEscapesLiteralAt(t *testing.T) {
	v, err := stringArg("name", "@@handle")
	if err != nil || v != "@handle" {
		t.Fatalf("%q %v", v, err)
	}
	if _, err := stringArg("name", "@/definitely/missing/file"); err == nil {
		t.Fatal("missing file must error")
	}
	v, _ = stringArg("name", "plain")
	if v != "plain" {
		t.Fatal(v)
	}
}

func TestEnumSpecParsesShortFormsAndCase(t *testing.T) {
	e := enumSpec{Values: []string{"OPERATOR_AND", "OPERATOR_OR"}, Short: []string{"and", "or"}}
	for raw, want := range map[string]string{"OPERATOR_AND": "OPERATOR_AND", "and": "OPERATOR_AND", "OR": "OPERATOR_OR", "operator_or": "OPERATOR_OR"} {
		got, err := e.parse("op", raw)
		if err != nil || got != want {
			t.Fatalf("%s: %q %v", raw, got, err)
		}
	}
	_, err := e.parse("op", "xor")
	if err == nil || !strings.Contains(err.Error(), "valid: and, or") {
		t.Fatalf("invalid value message: %v", err)
	}
}

func TestScalarValuesKeepNumberPrecision(t *testing.T) {
	v, err := scalarValue("n", "12345678901234567890", scalarInt, nil)
	if err != nil || mustJSON(t, v) != "12345678901234567890" {
		t.Fatalf("%v %v", v, err)
	}
	if _, err := scalarValue("n", "1.5", scalarInt, nil); err == nil {
		t.Fatal("float for int")
	}
	b, _ := scalarValue("b", "true", scalarBool, nil)
	if b != true {
		t.Fatal(b)
	}
}

func TestEntriesAndKV(t *testing.T) {
	k, v, err := parseKV("label", "team=platform=core")
	if err != nil || k != "team" || v != "platform=core" {
		t.Fatalf("%s %s %v", k, v, err)
	}
	if _, _, err := parseKV("label", "novalue"); err == nil {
		t.Fatal("missing =")
	}
	k, typed, err := parseEntry("data", `limits:={"seats": 5}`)
	if err != nil || k != "limits" || mustJSON(t, typed) != `{"seats":5}` {
		t.Fatalf("%s %v %v", k, typed, err)
	}
	_, plain, _ := parseEntry("data", "plan=5")
	if plain != "5" {
		t.Fatalf("untyped entry stays a string: %v", plain)
	}
	for raw, want := range map[string]bool{"a=b": true, "a:=1": true, "{\"a\":1}": false, "@file": false, "-": false, "=x": false, "a b=c": false} {
		if looksLikeEntry(raw) != want {
			t.Fatalf("looksLikeEntry(%q) != %v", raw, want)
		}
	}
}

func TestShorthandItems(t *testing.T) {
	spec := shorthandSpec{Fields: []shorthandField{
		{Wire: "memoryLayerId", Key: "memory-layer-id", Required: true},
		{Wire: "limit", Key: "limit", Kind: scalarInt},
		{Wire: "mode", Key: "mode", Enum: &enumSpec{Values: []string{"MODE_FAST"}, Short: []string{"fast"}}},
	}}
	item, err := parseShorthand("mc", `memory-layer-id=ml_1,limit=3,mode=fast`, spec)
	if err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, item); got != `{"limit":3,"memoryLayerId":"ml_1","mode":"MODE_FAST"}` {
		t.Fatal(got)
	}
	if _, err := parseShorthand("mc", "limit=3", spec); err == nil || !strings.Contains(err.Error(), "memory-layer-id is required") {
		t.Fatalf("required key: %v", err)
	}
	if _, err := parseShorthand("mc", "nope=1", spec); err == nil || !strings.Contains(err.Error(), "unknown key") {
		t.Fatalf("unknown key: %v", err)
	}
	quoted, _ := parseShorthand("mc", `memory-layer-id="a,b"`, spec)
	if quoted["memoryLayerId"] != "a,b" {
		t.Fatalf("quoted comma: %v", quoted)
	}

	pair := shorthandSpec{Fields: []shorthandField{{Wire: "name", Key: "name"}, {Wire: "value", Key: "value"}}, PairKey: "name", PairValue: "value"}
	item, err = parseShorthand("secret", "GITHUB_TOKEN=abc,def=1", pair)
	if err != nil || item["name"] != "GITHUB_TOKEN" || item["value"] != "abc,def=1" {
		t.Fatalf("pair form keeps the whole value: %v %v", item, err)
	}
	item, _ = parseShorthand("secret", "name=n,value=v", pair)
	if item["name"] != "n" || item["value"] != "v" {
		t.Fatalf("explicit pair keys: %v", item)
	}
}

func TestBuilderLayersFileDocumentAndLeaf(t *testing.T) {
	b := newBodyBuilder()
	if err := b.applyFile("file", tempDoc(t, `{"metadata":{"name":"from-file","externalId":"x"},"spec":{"description":"d"}}`), nil, false); err != nil {
		t.Fatal(err)
	}
	if err := b.applyDoc("metadata", []string{"metadata"}, `name: from-doc`, nil, false); err != nil {
		t.Fatal(err)
	}
	if err := b.set("name", []string{"metadata", "name"}, "from-flag"); err != nil {
		t.Fatal(err)
	}
	if err := b.appendItem("overlay", []string{"spec", "overlays"}, map[string]any{"key": "k"}); err != nil {
		t.Fatal(err)
	}
	if err := b.putEntry("label", []string{"metadata", "labels"}, "team", "x"); err != nil {
		t.Fatal(err)
	}
	got := mustJSON(t, b.body)
	want := `{"metadata":{"externalId":"x","labels":{"team":"x"},"name":"from-flag"},"spec":{"description":"d","overlays":[{"key":"k"}]}}`
	if got != want {
		t.Fatalf("got %s\nwant %s", got, want)
	}
	if mask := b.updateMask(""); mask != "metadata,metadata.labels,metadata.name,spec,spec.overlays" {
		t.Fatalf("mask %q", mask)
	}
	if err := b.set("x", []string{"metadata", "name", "deeper"}, 1); err == nil {
		t.Fatal("setting below a scalar must error")
	}
}

func adapterUnion() unionSpec {
	return unionSpec{
		Flag: "adapter", Path: []string{"spec", "adapter"}, Discriminator: "type", Required: true, Inferable: true,
		Arms: []unionArm{
			{Tag: "mcp", Keys: []string{"mcp"}, Init: []string{"mcp"}},
			{Tag: "http", Keys: []string{"http"}, Init: []string{"http"}},
			{Tag: "remoteFeed", Keys: []string{"remoteFeed"}},
		},
	}
}

func TestUnionInferredFromArmInputs(t *testing.T) {
	b := newBodyBuilder()
	_ = b.set("mcp-url", []string{"spec", "adapter", "mcp", "url"}, "https://x")
	if err := b.resolveUnion(adapterUnion()); err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, b.body); got != `{"spec":{"adapter":{"mcp":{"url":"https://x"},"type":"mcp"}}}` {
		t.Fatal(got)
	}
}

func TestUnionExplicitTagInitialisesRequiredObjects(t *testing.T) {
	b := newBodyBuilder()
	u := adapterUnion()
	if err := b.applyUnionFlag(u, "HTTP", nil, false); err != nil {
		t.Fatal(err)
	}
	if err := b.resolveUnion(u); err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, b.body); got != `{"spec":{"adapter":{"http":{},"type":"http"}}}` {
		t.Fatal(got)
	}
	// Kebab spelling of a camelCase tag.
	b = newBodyBuilder()
	_ = b.applyUnionFlag(u, "remote-feed", nil, false)
	_ = b.resolveUnion(u)
	if b.body["spec"].(map[string]any)["adapter"].(map[string]any)["type"] != "remoteFeed" {
		t.Fatal(mustJSON(t, b.body))
	}
	if err := b.applyUnionFlag(u, "nope", nil, false); err == nil || !strings.Contains(err.Error(), "valid: mcp, http, remoteFeed") {
		t.Fatalf("bad tag: %v", err)
	}
}

func TestUnionConflictsAreUsageErrors(t *testing.T) {
	b := newBodyBuilder()
	_ = b.set("mcp-url", []string{"spec", "adapter", "mcp", "url"}, "u")
	_ = b.set("http-base-url", []string{"spec", "adapter", "http", "baseUrl"}, "b")
	err := b.resolveUnion(adapterUnion())
	if err == nil || !strings.Contains(err.Error(), "--mcp-url and --http-base-url are mutually exclusive (--adapter arms mcp and http)") {
		t.Fatalf("two arms: %v", err)
	}
	b = newBodyBuilder()
	_ = b.set("mcp-url", []string{"spec", "adapter", "mcp", "url"}, "u")
	_ = b.applyUnionFlag(adapterUnion(), "http", nil, false)
	err = b.resolveUnion(adapterUnion())
	if err == nil || !strings.Contains(err.Error(), "--adapter http contradicts --mcp-url") {
		t.Fatalf("explicit vs inputs: %v", err)
	}
	b = newBodyBuilder()
	_ = b.applyDoc("spec", []string{"spec"}, `adapter: {type: mcp, mcp: {}}`, nil, false)
	_ = b.applyUnionFlag(adapterUnion(), "http", nil, false)
	err = b.resolveUnion(adapterUnion())
	if err == nil || !strings.Contains(err.Error(), "contradicts type") {
		t.Fatalf("explicit vs document: %v", err)
	}
}

func TestNestedUnionOnlyResolvesInsideItsArm(t *testing.T) {
	nested := unionSpec{
		Flag: "openapi", Path: []string{"spec", "adapter", "openapi"}, Discriminator: "type", Required: true, Inferable: true,
		Parent: &unionParent{Path: []string{"spec", "adapter"}, Discriminator: "type", Tag: "openapi"},
		Arms:   []unionArm{{Tag: "url", Keys: []string{"url"}}, {Tag: "uploadId", Keys: []string{"uploadId"}}},
	}
	b := newBodyBuilder()
	_ = b.set("mcp-url", []string{"spec", "adapter", "mcp", "url"}, "u")
	_ = b.resolveUnion(adapterUnion())
	if err := b.resolveUnion(nested); err != nil {
		t.Fatalf("unselected parent arm: %v", err)
	}
	b = newBodyBuilder()
	_ = b.set("openapi-url", []string{"spec", "adapter", "openapi", "url"}, "u")
	outer := adapterUnion()
	outer.Arms = append(outer.Arms, unionArm{Tag: "openapi", Keys: []string{"openapi"}})
	_ = b.resolveUnion(outer)
	if err := b.resolveUnion(nested); err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, b.body); got != `{"spec":{"adapter":{"openapi":{"type":"url","url":"u"},"type":"openapi"}}}` {
		t.Fatal(got)
	}
	b = newBodyBuilder()
	_ = b.set("mcp-url", []string{"spec", "adapter", "mcp", "url"}, "u")
	_ = b.resolveUnion(adapterUnion())
	_ = b.applyUnionFlag(nested, "url", nil, false)
	if err := b.resolveUnion(nested); err == nil || !strings.Contains(err.Error(), "not selected") {
		t.Fatalf("explicit tag for an unselected arm: %v", err)
	}
	// An explicit nested tag is itself enough to select the enclosing arm,
	// including when the nested arm has no other fields.
	b = newBodyBuilder()
	outer = adapterUnion()
	outer.Arms = append(outer.Arms, unionArm{Tag: "openapi", Keys: []string{"openapi"}})
	if err := b.applyUnionFlag(nested, "url", nil, false); err != nil {
		t.Fatal(err)
	}
	if err := b.resolveUnion(outer); err != nil {
		t.Fatalf("nested tag should select outer arm: %v", err)
	}
	if err := b.resolveUnion(nested); err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, b.body); got != `{"spec":{"adapter":{"openapi":{"type":"url"},"type":"openapi"}}}` {
		t.Fatal(got)
	}
}

func TestApplyFileReadsAPath(t *testing.T) {
	// YAML 1.1 reads bare y/n/yes/no as booleans; quote such strings.
	path := tempDoc(t, "metadata:\n  name: nectarine\n  externalId: \"n\"\n")
	b := newBodyBuilder()
	if err := b.applyFile("file", path, nil, false); err != nil {
		t.Fatal(err)
	}
	if mustJSON(t, b.body) != `{"metadata":{"externalId":"n","name":"nectarine"}}` {
		t.Fatal(mustJSON(t, b.body))
	}
	if err := newBodyBuilder().applyFile("file", "@"+path, nil, false); err != nil {
		t.Fatalf("@path also works: %v", err)
	}
}

func TestUnionRequiredAndOptional(t *testing.T) {
	b := newBodyBuilder()
	err := b.resolveUnion(adapterUnion())
	if err == nil || !strings.Contains(err.Error(), "--adapter is required (one of: mcp, http, remoteFeed)") {
		t.Fatalf("required: %v", err)
	}
	optional := adapterUnion()
	optional.Required = false
	if err := b.resolveUnion(optional); err != nil {
		t.Fatalf("absent optional union is fine: %v", err)
	}
	if _, ok := b.body["spec"]; ok {
		t.Fatal("nothing should be created for an absent optional union")
	}
	// A document supplied the tag already.
	b = newBodyBuilder()
	_ = b.applyDoc("spec", []string{"spec"}, `adapter: {type: mcp, mcp: {url: u}}`, nil, false)
	if err := b.resolveUnion(adapterUnion()); err != nil {
		t.Fatal(err)
	}
	// Ambiguous arms (not inferable) need the tag flag.
	ambiguous := adapterUnion()
	ambiguous.Inferable = false
	b = newBodyBuilder()
	_ = b.set("mcp-url", []string{"spec", "adapter", "mcp", "url"}, "u")
	if err := b.resolveUnion(ambiguous); err == nil || !strings.Contains(err.Error(), "--adapter is required") {
		t.Fatalf("ambiguous: %v", err)
	}
	// Inferability controls automatic selection, not conflict detection.
	_ = b.applyUnionFlag(ambiguous, "http", nil, false)
	if err := b.resolveUnion(ambiguous); err == nil || !strings.Contains(err.Error(), "contradicts --mcp-url") {
		t.Fatalf("explicit tag must still reject another arm when inference is disabled: %v", err)
	}
	// A malformed discriminator must not be silently overwritten from the
	// arm's other fields.
	b = newBodyBuilder()
	_ = b.applyDoc("adapter", []string{"spec", "adapter"}, `{"type":123,"mcp":{"url":"u"}}`, nil, false)
	if err := b.resolveUnion(adapterUnion()); err == nil || !strings.Contains(err.Error(), "type must be a string") {
		t.Fatalf("non-string discriminator: %v", err)
	}
}

const testSchema = `{
  "type": "object",
  "properties": {
    "metadata": {"$ref": "Metadata"},
    "spec": {"$ref": "Spec"},
    "updateMask": {"type": "string"}
  },
  "required": ["metadata", "spec"],
  "$defs": {
    "Metadata": {"type": "object", "required": ["name"], "properties": {"name": {"type": "string"}, "labels": {"type": "object", "additionalProperties": {"type": "string"}}}},
    "Spec": {"type": "object", "required": ["adapter"], "properties": {
      "adapter": {"$ref": "Adapter"},
      "season": {"$ref": "Season"},
      "overlays": {"type": "array", "items": {"$ref": "Overlay"}}
    }},
    "Adapter": {"oneOf": [{"$ref": "McpVariant"}, {"$ref": "HttpVariant"}], "discriminator": {"propertyName": "type"}},
    "McpVariant": {"type": "object", "required": ["type", "mcp"], "properties": {"type": {"const": "mcp"}, "mcp": {"$ref": "Mcp"}}},
    "Mcp": {"type": "object", "required": ["url"], "properties": {"url": {"type": "string"}}},
    "HttpVariant": {"type": "object", "required": ["type", "http"], "properties": {"type": {"const": "http"}, "http": {"type": "object", "properties": {"baseUrl": {"type": "string"}}}}},
    "Season": {"type": "string", "enum": ["SEASON_SPRING", "SEASON_AUTUMN"], "enumShort": {"spring": "SEASON_SPRING", "autumn": "SEASON_AUTUMN"}},
    "Overlay": {"type": "object", "required": ["key"], "properties": {"key": {"type": "string"}, "season": {"$ref": "Season"}}}
  }
}`

func TestSchemaStripsUnknownFieldsThroughUnionsAndLists(t *testing.T) {
	schema := parseBodySchema(testSchema)
	b := newBodyBuilder()
	doc := tempDoc(t, `{"metadata":{"id":"srv","name":"n","createdAt":"t"},"spec":{"adapter":{"type":"mcp","mcp":{"url":"u","state":"x"}},"overlays":[{"key":"k","junk":1}]},"state":"ACTIVE"}`)
	if err := b.applyFile("file", doc, schema, true); err == nil || !strings.Contains(err.Error(), "metadata.createdAt, metadata.id, spec.adapter.mcp.state, spec.overlays.0.junk, state") {
		t.Fatalf("strict lists every unknown path: %v", err)
	}
	b = newBodyBuilder()
	if err := b.applyFile("file", doc, schema, false); err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, b.body); got != `{"metadata":{"name":"n"},"spec":{"adapter":{"mcp":{"url":"u"},"type":"mcp"},"overlays":[{"key":"k"}]}}` {
		t.Fatal(got)
	}
	// Subtree documents are checked at their own node.
	b = newBodyBuilder()
	if err := b.applyDoc("metadata", []string{"metadata"}, `{"name":"n","id":"x"}`, schema, true); err == nil || !strings.Contains(err.Error(), "metadata.id") {
		t.Fatalf("subtree strict: %v", err)
	}
	// Without a discriminator, an early subtree check cannot choose a union
	// arm. Resolution stamps the tag; finish must then enforce strictness.
	b = newBodyBuilder()
	_ = b.applyDoc("adapter", []string{"spec", "adapter"}, `{"mcp":{"url":"u","junk":true}}`, schema, true)
	if err := b.resolveUnion(adapterUnion()); err != nil {
		t.Fatal(err)
	}
	if err := b.finish(schema, nil, true); err == nil || !strings.Contains(err.Error(), "spec.adapter.mcp.junk") {
		t.Fatalf("late union validation: %v", err)
	}
}

func TestFinishExpandsEnumShortFormsInsideDocuments(t *testing.T) {
	schema := parseBodySchema(testSchema)
	b := newBodyBuilder()
	_ = b.applyFile("file", tempDoc(t, `{"metadata":{"name":"n"},"spec":{"adapter":{"type":"mcp","mcp":{"url":"u"}},"season":"autumn","overlays":[{"key":"k","season":"Spring"}]}}`), schema, true)
	if err := b.finish(schema, nil, true); err != nil {
		t.Fatal(err)
	}
	spec := b.body["spec"].(map[string]any)
	if spec["season"] != "SEASON_AUTUMN" {
		t.Fatal(spec["season"])
	}
	if spec["overlays"].([]any)[0].(map[string]any)["season"] != "SEASON_SPRING" {
		t.Fatal(mustJSON(t, spec))
	}
	b = newBodyBuilder()
	_ = b.applyFile("file", tempDoc(t, `{"metadata":{"name":"n"},"spec":{"adapter":{"type":"mcp","mcp":{"url":"u"}},"season":"winter"}}`), schema, true)
	if err := b.finish(schema, nil, true); err == nil || !strings.Contains(err.Error(), `spec.season: invalid value "winter" (valid: autumn, spring)`) {
		t.Fatalf("invalid enum in document: %v", err)
	}
}

func TestFinishReportsDeepestRequiredPathsByFlag(t *testing.T) {
	schema := parseBodySchema(testSchema)
	flagFor := map[string]string{"metadata.name": "--name", "spec.adapter": "--adapter", "spec.adapter.mcp.url": "--mcp-url"}
	b := newBodyBuilder()
	err := b.finish(schema, flagFor, false)
	if err == nil || err.Error() != "required flag(s) not set: --name, --adapter" {
		t.Fatalf("empty body: %v", err)
	}
	b = newBodyBuilder()
	_ = b.set("name", []string{"metadata", "name"}, "n")
	_ = b.applyUnionFlag(adapterUnion(), "mcp", nil, false)
	_ = b.resolveUnion(adapterUnion())
	err = b.finish(schema, flagFor, false)
	if err == nil || err.Error() != "required flag(s) not set: --mcp-url" {
		t.Fatalf("arm required leaf: %v", err)
	}
	_ = b.set("mcp-url", []string{"spec", "adapter", "mcp", "url"}, "u")
	if err := b.finish(schema, flagFor, false); err != nil {
		t.Fatalf("complete body: %v", err)
	}
	// A required object with no required leaves is sent as {} rather than
	// demanded from the user.
	relaxed := parseBodySchema(strings.Replace(testSchema, `"Mcp": {"type": "object", "required": ["url"],`, `"Mcp": {"type": "object",`, 1))
	b = newBodyBuilder()
	_ = b.set("name", []string{"metadata", "name"}, "n")
	_ = b.applyUnionFlag(adapterUnion(), "mcp", nil, false)
	_ = b.resolveUnion(adapterUnion())
	if err := b.finish(relaxed, flagFor, false); err != nil {
		t.Fatalf("required object without required leaves: %v", err)
	}
	if got := mustJSON(t, b.body); got != `{"metadata":{"name":"n"},"spec":{"adapter":{"mcp":{},"type":"mcp"}}}` {
		t.Fatal(got)
	}
	// Optional envelopes (a patch) impose nothing when absent.
	patch := parseBodySchema(strings.Replace(testSchema, `"required": ["metadata", "spec"],`, "", 1))
	if err := newBodyBuilder().finish(patch, flagFor, false); err != nil {
		t.Fatalf("patch: %v", err)
	}
}

func TestWholeBodyDocumentsUseTheSameValidation(t *testing.T) {
	schema := parseBodySchema(`{
	  "type":"array",
	  "items":{"type":"object","required":["season"],"properties":{
	    "season":{"type":"string","enum":["SEASON_SPRING"],"enumShort":{"spring":"SEASON_SPRING"}}
	  }}
	}`)
	b := newBodyBuilder()
	raw, err := b.applyRootDocument("file", tempDoc(t, `[{"season":"spring","junk":true}]`), true, schema, false)
	if err != nil {
		t.Fatal(err)
	}
	raw, err = b.finishValue(schema, raw, nil, false)
	if err != nil {
		t.Fatal(err)
	}
	if got := mustJSON(t, raw); got != `[{"season":"SEASON_SPRING"}]` {
		t.Fatalf("validated whole-body list: %s", got)
	}
	if _, err := b.finishValue(schema, []any{map[string]any{}}, nil, false); err == nil || !strings.Contains(err.Error(), "0.season") {
		t.Fatalf("required field in whole-body list: %v", err)
	}

	enumSchema := parseBodySchema(`{"type":"string","enum":["MODE_FAST"],"enumShort":{"fast":"MODE_FAST"}}`)
	value, err := b.finishValue(enumSchema, "FAST", nil, false)
	if err != nil || value != "MODE_FAST" {
		t.Fatalf("root enum: %v %v", value, err)
	}
}

func TestSchemaAtWalksProperties(t *testing.T) {
	schema := parseBodySchema(testSchema)
	if n := schema.at([]string{"metadata", "labels"}); n == nil || n.AdditionalProperties == nil {
		t.Fatal("labels map")
	}
	if n := schema.at([]string{"spec", "adapter", "mcp"}); n != nil {
		t.Fatal("cannot see through a union without a value")
	}
	if !reflect.DeepEqual(schema.at([]string{"spec"}).Required, []string{"adapter"}) {
		t.Fatal("spec required")
	}
}
