// Code generated by redwood. DO NOT EDIT.
package commands

// Shared mechanics used by Redwood's generated, operation-specific command
// converters. The converters own which urfave accessors and wire fields are
// used; this file only handles external document sources and the final typed
// SDK decode.

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
)

// resolveInput expands a document input: "@path" reads the file, "-" reads
// stdin, and anything else is the literal document.
func resolveInput(raw string) (string, error) {
	switch {
	case raw == "-":
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return "", fmt.Errorf("reading stdin: %w", err)
		}
		return strings.TrimSpace(string(data)), nil
	case strings.HasPrefix(raw, "@"):
		data, err := os.ReadFile(raw[1:])
		if err != nil {
			return "", err
		}
		return strings.TrimSpace(string(data)), nil
	default:
		return raw, nil
	}
}

// decodeParams lets the generated SDK types perform the authoritative type
// conversion and validation after the generated converter has assembled wire
// values from urfave flags and optional documents.
func decodeParams(values map[string]any, target any) error {
	raw, err := json.Marshal(values)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(raw, target); err != nil {
		return fmt.Errorf("invalid parameters: %w", err)
	}
	return nil
}

// jsonArg parses a --flag JSON document (literal, @file, or - for stdin),
// failing with the flag name.
func jsonArg(name, raw string) (json.RawMessage, error) {
	resolved, err := resolveInput(raw)
	if err != nil {
		return nil, fmt.Errorf("--%s: %w", name, err)
	}
	if !json.Valid([]byte(resolved)) {
		return nil, fmt.Errorf("--%s: invalid JSON", name)
	}
	if resolved == "null" {
		return nil, fmt.Errorf("--%s: null is not a valid value; omit the flag instead", name)
	}
	return json.RawMessage(resolved), nil
}

// jsonSliceArg parses repeated --flag JSON documents.
func jsonSliceArg(name string, raws []string) ([]json.RawMessage, error) {
	out := make([]json.RawMessage, 0, len(raws))
	for _, raw := range raws {
		msg, err := jsonArg(name, raw)
		if err != nil {
			return nil, err
		}
		out = append(out, msg)
	}
	return out, nil
}
