// Code generated by redwood. DO NOT EDIT.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"text/tabwriter"

	cli "github.com/urfave/cli/v3"
	"sigs.k8s.io/yaml"
)

// addAlias clones the command at path onto the root under a new name, so a
// deeply nested command gains a top-level spelling. A shallow clone shares
// the target's flags and action; the path is validated at generation time,
// so a miss here is impossible short of hand-editing — degrade silently.
func addAlias(root *cli.Command, name string, path ...string) {
	cmds := root.Commands
	var target *cli.Command
	for _, seg := range path {
		target = nil
		for _, c := range cmds {
			if c.Name == seg {
				target = c
				break
			}
		}
		if target == nil {
			return
		}
		cmds = target.Commands
	}
	clone := *target
	clone.Name = name
	root.Commands = append(root.Commands, &clone)
}

// printJSON writes v to stdout as indented JSON (single-response commands).
func printJSON(v any) error {
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

// printJSONLine writes v to stdout as one compact JSON document per line
// (NDJSON). Streaming commands use this so every line parses independently —
// an unbounded stream never forms a single JSON document, and consumers
// (jq -c, line readers) must not need an incremental JSON framer.
func printJSONLine(v any) error {
	return json.NewEncoder(os.Stdout).Encode(v)
}

// displayColumn is one statically-resolved table/extended column: header
// plus JSON WIRE path segments into the response projection. truncate > 0
// caps the TABLE cell width (runes); extended output is never cut.
type displayColumn struct {
	header   string
	path     []string
	truncate int
}

// displayMode resolves the effective mode: command-local flag, then the
// root flag, then the configured default.
func displayMode(cmd *cli.Command, def string) string {
	if cmd.IsSet("display") {
		return cmd.String("display")
	}
	if v := cmd.Root().String("display"); v != "" {
		return v
	}
	return def
}

// lookupPath traverses dot-separated object keys through a decoded JSON
// value. Reported ok=false for any missing segment or non-object step.
func lookupPath(value any, path []string) (any, bool) {
	current := value
	for _, key := range path {
		obj, isObj := current.(map[string]any)
		if !isObj {
			return nil, false
		}
		next, present := obj[key]
		if !present {
			return nil, false
		}
		current = next
	}
	return current, true
}

// truncateCell caps a rendered cell at width runes, marking the cut with an
// ellipsis; width <= 0 leaves it untouched.
func truncateCell(text string, width int) string {
	if width <= 0 {
		return text
	}
	runes := []rune(text)
	if len(runes) <= width {
		return text
	}
	if width == 1 {
		return "…"
	}
	return string(runes[:width-1]) + "…"
}

// renderCell prints scalars plainly, missing/null as "-", composites as
// compact JSON, and makes embedded newlines/tabs visible so one value
// cannot corrupt table structure. Values are never truncated here — the
// table renderer applies a column's truncate width, extended never does.
func renderCell(v any, ok bool) string {
	if !ok || v == nil {
		return "-"
	}
	var text string
	switch tv := v.(type) {
	case string:
		text = tv
	case bool, float64, json.Number:
		text = fmt.Sprintf("%v", tv)
	default:
		raw, err := json.Marshal(tv)
		if err != nil {
			return "-"
		}
		text = string(raw)
	}
	text = strings.ReplaceAll(text, "\t", "\\t")
	text = strings.ReplaceAll(text, "\r", "\\r")
	return strings.ReplaceAll(text, "\n", "\\n")
}

// renderDisplay is the single output dispatcher for ordinary commands:
// json preserves the existing machine contract byte-for-byte; table and
// extended render the configured columns from a JSON projection of the
// response. Paginated tables render only the current page and report a
// next cursor on stderr so stdout rows stay clean.
func renderDisplay(mode string, columns []displayColumn, isPage bool, v any) error {
	if mode == "json" || mode == "" {
		return printJSON(v)
	}
	if mode == "yaml" {
		return printYAML(v)
	}
	raw, err := json.Marshal(v)
	if err != nil {
		return err
	}
	var projected any
	if err := json.Unmarshal(raw, &projected); err != nil {
		return err
	}
	rows := []any{projected}
	if isPage {
		obj, _ := projected.(map[string]any)
		items, _ := obj["items"].([]any)
		rows = items
		if cursor, _ := obj["nextCursor"].(string); cursor != "" {
			fmt.Fprintf(os.Stderr, "next cursor: %s\n", cursor)
		}
	}
	if mode == "table" {
		w := tabwriter.NewWriter(os.Stdout, 0, 4, 2, ' ', 0)
		headers := make([]string, len(columns))
		for i, c := range columns {
			headers[i] = c.header
		}
		fmt.Fprintln(w, strings.Join(headers, "\t"))
		for _, row := range rows {
			cells := make([]string, len(columns))
			for i, c := range columns {
				value, present := lookupPath(row, c.path)
				cells[i] = truncateCell(renderCell(value, present), c.truncate)
			}
			fmt.Fprintln(w, strings.Join(cells, "\t"))
		}
		return w.Flush()
	}
	// extended: psql-style vertical records with the SAME columns.
	width := 0
	for _, c := range columns {
		if len(c.header) > width {
			width = len(c.header)
		}
	}
	for i, row := range rows {
		fmt.Fprintf(os.Stdout, "-[ RECORD %d ]-\n", i+1)
		for _, c := range columns {
			value, present := lookupPath(row, c.path)
			fmt.Fprintf(os.Stdout, "%-*s | %s\n", width, c.header, renderCell(value, present))
		}
	}
	return nil
}

// isOneOf reports whether value is one of the declared enum choices
// (exact, case-sensitive — wire values are canonical).
func isOneOf(value string, choices []string) bool {
	for _, c := range choices {
		if value == c {
			return true
		}
	}
	return false
}

// stdinBudget enforces the '-' contract BEFORE any read: stdin can supply
// at most one input per invocation (a second '-' would otherwise see
// drained input), and a doomed command must not block on stdin.
func stdinBudget(raws []string) error {
	count := 0
	for _, raw := range raws {
		if raw == "-" {
			count++
		}
	}
	if count > 1 {
		return fmt.Errorf("'-' (stdin) may supply at most one input per command; use @file or literal values for the others")
	}
	return nil
}

// printYAML writes v as a YAML document.
func printYAML(v any) error {
	raw, err := json.Marshal(v)
	if err != nil {
		return err
	}
	out, err := yaml.JSONToYAML(raw)
	if err != nil {
		return err
	}
	_, err = os.Stdout.Write(out)
	return err
}

// printDocument renders a --dry-run body: YAML unless json was asked for.
func printDocument(mode string, v any) error {
	if mode == "json" {
		return printJSON(v)
	}
	return printYAML(v)
}
